### ISSUE TITLE
Problem updating

### ISSUE THREAD

**Issue by Rofii** [FomTarro/vts-heartrate#28]
I deleted the 1.3.0 folder and unzipped the 1.3.1 folder, but nothing changed. It still tells me I'm on 1.3.0 and to update to 1.3.1.

**Comment by Rofii** [comment]
Update: I redownloaded the zip from itch.io and this time it worked. Very confusing lmao.

**Comment by FomTarro** [comment]
Glad it worked out! 😅 Was the first time you tried to download from the git release here? Maybe I uploaded the wrong version here.

**Comment by Rofii** [comment]
Nope it was from itch.io but I downloaded the zip originally 25 hours ago and the current 1.3.1 on itch says it was uploaded only 21 hours ago. 🤔

**Comment by FomTarro** [comment]
I probably uploaded the old version to Itch initially. I can't reproduce the error but it sounds like the correct versions are where they belong now.
